model:
  input_height: 224
  input_width: 224
  input_channels: 3
  num_classes: 2
  architecture: resnet50
  optimizer: SGD # choose from  [SGD, Adam, RMSprop]
  learning_rate: 0.001
  batch_size: 32
  num_epochs: 10
  num_gpus: 1
  num_workers: 4
  log_interval: 10
  checkpoint_interval: 1
  pretrained: false
  pretrained_model_path: null
data:
  root_dir: /data
  train_dir: train
  val_dir: val
  test_dir: test
  train_transforms:
    - name: Resize
      params: [256]
    - name: RandomCrop
      params: [224]
    - name: RandomHorizontalFlip
      params: [0.5]
    - name: ToTensor
    - name: Normalize
      params: [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]
  
